/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TestUserInterface extends utils.Interface {
  contractName: "TestUser";
  functions: {
    "failClaimFromAuction(address)": FunctionFragment;
    "failClaimFromSale(address)": FunctionFragment;
    "mintNFTandCreateAuction(address,address,address)": FunctionFragment;
    "mintNFTandCreateSale(address,address)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "failClaimFromAuction",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "failClaimFromSale",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintNFTandCreateAuction",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintNFTandCreateSale",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "failClaimFromAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "failClaimFromSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintNFTandCreateAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintNFTandCreateSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TestUser extends BaseContract {
  contractName: "TestUser";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestUserInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    failClaimFromAuction(
      auctionContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    failClaimFromSale(
      saleContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mintNFTandCreateAuction(
      nftContract: string,
      auctionContract: string,
      approvedContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mintNFTandCreateSale(
      nftContract: string,
      saleContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  failClaimFromAuction(
    auctionContract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  failClaimFromSale(
    saleContract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mintNFTandCreateAuction(
    nftContract: string,
    auctionContract: string,
    approvedContract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mintNFTandCreateSale(
    nftContract: string,
    saleContract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC1155Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BigNumberish,
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    failClaimFromAuction(
      auctionContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    failClaimFromSale(
      saleContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    mintNFTandCreateAuction(
      nftContract: string,
      auctionContract: string,
      approvedContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    mintNFTandCreateSale(
      nftContract: string,
      saleContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    failClaimFromAuction(
      auctionContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    failClaimFromSale(
      saleContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mintNFTandCreateAuction(
      nftContract: string,
      auctionContract: string,
      approvedContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mintNFTandCreateSale(
      nftContract: string,
      saleContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    failClaimFromAuction(
      auctionContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    failClaimFromSale(
      saleContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mintNFTandCreateAuction(
      nftContract: string,
      auctionContract: string,
      approvedContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mintNFTandCreateSale(
      nftContract: string,
      saleContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
